services:
  # generate configs using the anyconf utility
  generateconfig-env:
    profiles: [env]
    build:
      context: .
      dockerfile: Dockerfile-generateconfig-env
    volumes:
      - ./:/code

  generateconfig-anyconf:
    build:
      context: .
      dockerfile: Dockerfile-generateconfig-anyconf
    profiles: [setup]
    restart: on-failure
    env_file:
      - path: .env
        required: true
    volumes:
      - ./:/code
      - "./storage/:/code/storage"

  # processing any-sync-* configs
  generateconfig-processing:
    depends_on:
      generateconfig-anyconf:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: Dockerfile-generateconfig-processing
    profiles: [setup]
    restart: on-failure
    env_file:
      - path: .env
        required: true
    volumes:
      - ./:/code
      - "./storage/:/code/storage"

  mongo-1:
    depends_on:
      generateconfig-processing:
        condition: service_completed_successfully
    image: "mongo:${MONGO_VERSION}"
    restart: unless-stopped
    command: ["--replSet", "${MONGO_REPLICA_SET}", "--port", "${MONGO_1_PORT}"]
    profiles: [setup]
    env_file:
      - path: .env
        required: true
    volumes:
      - "./storage/mongo-1/:/data/db"
    healthcheck:
      test: test $$(mongosh --port ${MONGO_1_PORT} --quiet --eval "try {rs.initiate({_id:'${MONGO_REPLICA_SET}',members:[{_id:0,host:\"mongo-1:${MONGO_1_PORT}\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

  redis:
    depends_on:
      generateconfig-processing:
        condition: service_completed_successfully
    image: "redis/redis-stack-server:${REDIS_VERSION}"
    restart: unless-stopped
    command: ["redis-server", "--port", "${REDIS_PORT}", "--dir", "/data/", "--appendonly", "yes", "--maxmemory", "${REDIS_MAXMEMORY}", "--maxmemory-policy", "noeviction", "--protected-mode", "no", "--loadmodule", "/opt/redis-stack/lib/redisbloom.so"]
    profiles: [setup]
    env_file:
      - path: .env
        required: true
    volumes:
      - "./storage/redis/:/data/"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "-p", "${REDIS_PORT}", "incr", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

  minio:
    image: "minio/minio:${MINIO_VERSION}"
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":${MINIO_WEB_PORT}", "--address", ":${MINIO_PORT}"]
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY}"
    profiles: [setup]
    env_file:
      - path: .env
        required: true
    volumes:
      - "./storage/minio:/data"
    ports:
      - 9001:9000
      - 9002:9001
    healthcheck:
      test: bash -c ':> /dev/tcp/127.0.0.1/${MINIO_PORT}' || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      default:
        aliases:
          - "${MINIO_BUCKET}.minio" # <bucket-name>.<endpoint-name>

  create-bucket:
    image: minio/mc:latest
    profiles: [initialsetup]
    restart: "no"
    env_file:
      - path: .env
        required: true
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http:/minio:${MINIO_PORT} '${AWS_ACCESS_KEY_ID}' '${AWS_SECRET_ACCESS_KEY}') do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/${MINIO_BUCKET};
      exit 0;
      "

  any-sync-coordinator_bootstrap:
    image: "ghcr.io/anyproto/any-sync-coordinator:${ANY_SYNC_COORDINATOR_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    volumes:
      - ./etc/any-sync-coordinator/:/etc/any-sync-coordinator/
    restart: "no"
    command: ["/bin/any-sync-confapply", "-c", "/etc/any-sync-coordinator/config.yml", "-n", "/etc/any-sync-coordinator/network.yml", "-e"]

  any-sync-coordinator:
    image: "ghcr.io/anyproto/any-sync-coordinator:${ANY_SYNC_COORDINATOR_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator_bootstrap:
        condition: service_completed_successfully
    ports:
      - "${ANY_SYNC_COORDINATOR_PORT}:${ANY_SYNC_COORDINATOR_PORT}"
      - "${ANY_SYNC_COORDINATOR_QUIC_PORT}:${ANY_SYNC_COORDINATOR_QUIC_PORT}/udp"
      - 8005:8000
    volumes:
      - ./etc/any-sync-coordinator/:/etc/any-sync-coordinator/
      - "./storage/networkStore/any-sync-coordinator/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  any-sync-filenode:
    image: "ghcr.io/anyproto/any-sync-filenode:${ANY_SYNC_FILENODE_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator:
        condition: service_started
    ports:
      - "${ANY_SYNC_FILENODE_PORT}:${ANY_SYNC_FILENODE_PORT}"
      - "${ANY_SYNC_FILENODE_QUIC_PORT}:${ANY_SYNC_FILENODE_QUIC_PORT}/udp"
      - 8004:8000
    volumes:
      - ./etc/any-sync-filenode/:/etc/any-sync-filenode/
      - ./etc/.aws:/root/.aws:ro
      - "./storage/networkStore/any-sync-filenode/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  any-sync-node-1:
    image: "ghcr.io/anyproto/any-sync-node:${ANY_SYNC_NODE_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator:
        condition: service_started
    ports:
      - "${ANY_SYNC_NODE_1_PORT}:${ANY_SYNC_NODE_1_PORT}"
      - "${ANY_SYNC_NODE_1_QUIC_PORT}:${ANY_SYNC_NODE_1_QUIC_PORT}/udp"
      - 8081:8080
      - 8001:8000
    volumes:
      - ./etc/any-sync-node-1/:/etc/any-sync-node/
      - "./storage/any-sync-node-1/:/storage/"
      - "./storage/networkStore/any-sync-node-1/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  any-sync-node-2:
    image: "ghcr.io/anyproto/any-sync-node:${ANY_SYNC_NODE_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator:
        condition: service_started
    ports:
      - "${ANY_SYNC_NODE_2_PORT}:${ANY_SYNC_NODE_2_PORT}"
      - "${ANY_SYNC_NODE_2_QUIC_PORT}:${ANY_SYNC_NODE_2_QUIC_PORT}/udp"
      - 8082:8080
      - 8002:8000
    volumes:
      - ./etc/any-sync-node-2/:/etc/any-sync-node/
      - "./storage/any-sync-node-2/:/storage/"
      - "./storage/networkStore/any-sync-node-2/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  any-sync-node-3:
    image: "ghcr.io/anyproto/any-sync-node:${ANY_SYNC_NODE_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator:
        condition: service_started
    ports:
      - "${ANY_SYNC_NODE_3_PORT}:${ANY_SYNC_NODE_3_PORT}"
      - "${ANY_SYNC_NODE_3_QUIC_PORT}:${ANY_SYNC_NODE_3_QUIC_PORT}/udp"
      - 8083:8080
      - 8003:8000
    volumes:
      - ./etc/any-sync-node-3/:/etc/any-sync-node/
      - "./storage/any-sync-node-3/:/storage/"
      - "./storage/networkStore/any-sync-node-3/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  any-sync-consensusnode:
    image: "ghcr.io/anyproto/any-sync-consensusnode:${ANY_SYNC_CONSENSUSNODE_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    depends_on:
      any-sync-coordinator:
        condition: service_started
    ports:
      - "${ANY_SYNC_CONSENSUSNODE_PORT}:${ANY_SYNC_CONSENSUSNODE_PORT}"
      - "${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}:${ANY_SYNC_CONSENSUSNODE_QUIC_PORT}/udp"
      - 8006:8000
    volumes:
      - ./etc/any-sync-consensusnode/:/etc/any-sync-consensusnode/
      - "./storage/networkStore/any-sync-consensusnode/:/networkStore/"
    deploy:
      resources:
        limits:
          memory: ${ANY_SYNC_DAEMONS_MEMORY_LIMIT:-}
    restart: unless-stopped

  # any-sync-netcheck
  netcheck:
    image: "ghcr.io/anyproto/any-sync-tools:${ANY_SYNC_TOOLS_VERSION}"
    profiles: [main]
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    depends_on:
      - any-sync-consensusnode
      - any-sync-filenode
      - any-sync-coordinator
      - any-sync-node-1
      - any-sync-node-2
      - any-sync-node-3
    volumes:
      - ./:/code
      - "./storage/:/code/storage"
    command: ["tail", "-f", "/dev/null"]
    stop_signal: SIGKILL
    tty: true
    healthcheck:
      test: any-sync-netcheck -c /code/storage/docker-generateconfig/nodes.yml 2>&1| grep -P 'netcheck\s+success'
      interval: 60s
      start_period: 5s
